/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myjniapplication_JniUtil */

#ifndef _Included_com_example_myjniapplication_JniUtil
#define _Included_com_example_myjniapplication_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myjniapplication_JniUtil
 * Method:    testJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myjniapplication_JniUtil_testJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
